// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_rw6l8rED-41LBxg5zYsKsmsdYwFL8A',
    appId: '1:500744941030:web:0fe32fbb8e811c680afa27',
    messagingSenderId: '500744941030',
    projectId: 'freelydz',
    authDomain: 'freelydz.firebaseapp.com',
    storageBucket: 'freelydz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrcJO1Pw399hwsrnoDprleMAPqsulG2tU',
    appId: '1:500744941030:android:615714f1baaa20260afa27',
    messagingSenderId: '500744941030',
    projectId: 'freelydz',
    storageBucket: 'freelydz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNY4QOPqYbPc2nWCYr15oncs4Cu0KZcv0',
    appId: '1:500744941030:ios:cf1fe661bb209c780afa27',
    messagingSenderId: '500744941030',
    projectId: 'freelydz',
    storageBucket: 'freelydz.appspot.com',
    iosBundleId: 'com.example.flut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNY4QOPqYbPc2nWCYr15oncs4Cu0KZcv0',
    appId: '1:500744941030:ios:cf1fe661bb209c780afa27',
    messagingSenderId: '500744941030',
    projectId: 'freelydz',
    storageBucket: 'freelydz.appspot.com',
    iosBundleId: 'com.example.flut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_rw6l8rED-41LBxg5zYsKsmsdYwFL8A',
    appId: '1:500744941030:web:d36fe5cd38e8348c0afa27',
    messagingSenderId: '500744941030',
    projectId: 'freelydz',
    authDomain: 'freelydz.firebaseapp.com',
    storageBucket: 'freelydz.appspot.com',
  );
}
